[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "weak_to_strong"
version = "0.0.1"
authors = [
  { name="OpenAI", email="generalization@openai.com" },
]
description = "Weak-to-strong generalization"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies=[
  "torch ~= 2.1",
  "numpy ~= 1.24",
  "transformers ~= 4.36",
  "datasets ~= 2.14",
  "fire ~= 0.4",
  "accelerate ~= 0.25",
  "transformers-stream-generator ~= 0.0.4",
  "torch_optimizer ~= 0.3",
  "wandb ~= 0.16.1",
  "peft ~= 0.7.1",
  "scikit-learn ~= 1.3.2",
  "pynvml ~= 11.5",
  "tiktoken ~= 0.6.0",
  "einops ~= 0.7.0",
]
