batch_size: 32
eval_batch_size: 32
max_ctx: 1024
ds_name: "sciq"
n_train_docs: 20000
n_inference_docs: null
n_test_docs: 1000
model_size: "gpt2"
lr: null
optim: null
epochs: 1
seed: 0
train_with_dropout: false
linear_probe: false
lr_schedule: "cosine_anneal"
eval_every: 10000000
load_best_model_at_end: false
save_total_limit: 1
disable_lora: false
model_cfg_name: null
loss: null
weak_labels_path: null
store_grads: false
d_downsample: 10000000
force_retrain: false
minibatch_size_per_replica: null
results_folder: "/tmp/results"
sweep_subfolder: "default"
save_every: 1000000
skip_if_exists: false
